version: '3'
services:
  web:
    build: .
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=bot_agent
    ports:
      - "3306:3306"
    command: --sql_mode=""