// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bot": {
            "post": {
                "description": "见原始文档https://newtestchatbot.wul.ai/core/engine/dm/openapi.json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "botAgent"
                ],
                "summary": "代理机器人Api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/flush": {
            "post": {
                "description": "点击200 Successful Response查看具体接口返回格式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "botAgent"
                ],
                "summary": "刷新统计数据缓存",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/stats": {
            "post": {
                "description": "点击200 Successful Response查看具体接口返回格式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "botAgent"
                ],
                "summary": "获取知识点TopN",
                "parameters": [
                    {
                        "description": " ",
                        "name": "n",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StatsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StatsResponse"
                            }
                        }
                    }
                }
            }
        },
        "/top": {
            "post": {
                "description": "点击200 Successful Response查看具体接口返回格式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "botAgent"
                ],
                "summary": "获取知识点TopN（无缓存）",
                "parameters": [
                    {
                        "description": " ",
                        "name": "n",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StatsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StatsResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.StatsRequest": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "n": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "model.StatsResponse": {
            "type": "object",
            "properties": {
                "cnt": {
                    "type": "integer"
                },
                "intent_id": {
                    "type": "string"
                },
                "intent_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
