// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chatbot/v1alpha1/agents/{agentId}/channels/{channelId}/getReply": {
            "post": {
                "description": "入参出参均与原始文档保持一致 https://demo.laiye.com:8083/chatbot-openapi/swagger-ui/#/ChannelReplyService/ChannelReplyService_GetReply",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "botAgent"
                ],
                "summary": "代理机器人Api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/chatbot/v1alpha1/agents/{agentId}/stats/topn": {
            "post": {
                "description": "点击200 Successful Response查看具体接口返回格式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "botAgent"
                ],
                "summary": "按枚举范围统计知识点TopN",
                "parameters": [
                    {
                        "description": "控制参数",
                        "name": "n",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DurationStatsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.IntentResult"
                            }
                        }
                    }
                }
            }
        },
        "/count": {
            "get": {
                "description": "返回bot_response总行数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "开发测试"
                ],
                "summary": "总记录数",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/flush": {
            "get": {
                "description": "整理90天内的bot_response表数据并写入daily_intent；刷新昨日、近7天、近30天、近90天的TopN缓存结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "开发测试"
                ],
                "summary": "整理历史数据并刷新缓存",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/init": {
            "get": {
                "description": "agent_id=[a1,a2] intent_id=[0,1,2,3]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "开发测试"
                ],
                "summary": "写入一些模拟调用机器人api数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/time": {
            "get": {
                "description": "打印现在、今天、昨天、x天前等时间段的unix秒，unix天",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "开发测试"
                ],
                "summary": "打印当前unixTime等信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/topn": {
            "post": {
                "description": "点击200 Successful Response查看具体接口返回格式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "开发测试"
                ],
                "summary": "按精确范围统计知识点TopN",
                "parameters": [
                    {
                        "description": " ",
                        "name": "n",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ExactStatsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.IntentResult"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.DurationStatsRequest": {
            "type": "object",
            "required": [
                "n"
            ],
            "properties": {
                "duration": {
                    "description": "duration-查询的时间范围 枚举类型：0.昨天 1.过去7天 2.过去30天 3.过去90天 4.上周汇总 5.上月汇总\" enum:\"0,1,2,3,4,5",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 0
                },
                "n": {
                    "description": "检索数量前n的intent信息，n允许范围[1,1000]",
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                }
            }
        },
        "model.ExactStatsRequest": {
            "type": "object",
            "required": [
                "end_time",
                "n",
                "start_time"
            ],
            "properties": {
                "agent_id": {
                    "description": "只检索这个id对应的agent（机器人）产生的记录",
                    "type": "string"
                },
                "end_time": {
                    "description": "检索范围的结束时间 unix时间戳",
                    "type": "integer",
                    "minimum": 0
                },
                "n": {
                    "description": "检索数量前n的intent信息，n允许范围[1,1000]",
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "start_time": {
                    "description": "检索范围的起始时间 unix时间戳",
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "model.IntentResult": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "该记录对应的agent",
                    "type": "string"
                },
                "count": {
                    "description": "按当前条件统计到的数量",
                    "type": "integer"
                },
                "intent_id": {
                    "description": "知识点唯一id",
                    "type": "string"
                },
                "intent_name": {
                    "description": "知识点最新名称",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
